### ISSUE TITLE
 [Feature Request] provide user downloadable builds

### ISSUE THREAD

**Issue by boomzero** [langningchen/OJTool#2]
You can use Github actions to upload assets.

**Comment by langningchen** [comment]
@boomzero See: https://github.com/langningchen/OJTool/actions/runs/9771252546

**Comment by boomzero** [comment]
linux I suppose? It would be nice to compile for other platforms

**Comment by langningchen** [comment]
我没有增加跨平台功能

**Comment by boomzero** [comment]
Ad: If you need multiplatform, check out [quickSubmit](https://github.com/boomzero/quicksubmit)!

**Comment by langningchen** [comment]
@boomzero But, you only have XMOJ submission. The most I need is Luogu submit. By the way, I use my Ubuntu 24.04 LTS more often now.

**Comment by boomzero** [comment]
> @boomzero But, you only have XMOJ submission. The most I need is Luogu submit. By the way, I use my Ubuntu 24.04 LTS more often now.

Have you tried the luogu VSCode plugin? It is a very mature and feature-rich plugin, and it has a GUI.
qsm is designed to be simple, and the fact that it only supports xmoj is intentional.

**Comment by langningchen** [comment]
The plugin has some problems, including the captcha and some incompatibilities.

**Comment by boomzero** [comment]
Perhaps file an issue there?

**Comment by langningchen** [comment]
I'm lazy. 😅
