### ISSUE TITLE
add xmoj cid

### ISSUE THREAD

**Issue by boomzero** [langningchen/OJTool#4]
for submitting to contests

**Comment by boomzero** [comment]
Hello?

**Comment by boomzero** [comment]
@langningchen

**Comment by langningchen** [comment]
But, I do not use XMOJ anymore......

**Comment by langningchen** [comment]
PR welcome

**Comment by boomzero** [comment]
You can copy https://github.com/boomzero/quicksubmit if you want

**Comment by boomzero** [comment]
This however makes OJTool’s xmoj module useless
